apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    type: kafka
spec:
  type: NodePort
  selector:
    type: kafka-deployment
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
      targetPort: 9092