apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: zookeeper-deployment
  template:
    metadata:
      labels:
        type: zookeeper-deployment
    spec:
      containers:
        - name: zoo
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"