apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-elastic-route
  labels:
    type: kafka-elastic-route
spec:
  replicas: 1
  selector:
    matchLabels:
      type: kafka-elastic-route
  template:
    metadata:
      labels:
        type: kafka-elastic-route
    spec:
      containers:
        - name: kafka-elastic-route
          image: shumyk/kafka-elastic-search-route
          ports:
            - containerPort: 8080
          env:
            - name: ELASTIC_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-elastic-route-secrets
                  key: elastic.hostname
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-elastic-route-secrets
                  key: elastic.username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-elastic-route-secrets
                  key: elastic.password
            - name: KAFKA_HOST
              value: kafka-service:9092
            - name: TOPIC_TWEETS_RAW
              value: tweets
          volumeMounts:
            - name: kafka-elastic-config
              mountPath: /config/
      volumes:
        - name: kafka-elastic-config
          configMap:
            name: kafka-elastic-route-configmap