apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-kafka-route
  labels:
    type: twitter-kafka-route
spec:
  replicas: 1
  selector:
    matchLabels:
      type: twitter-kafka-route
  template:
    metadata:
      labels:
        type: twitter-kafka-route
    spec:
      containers:
        - name: twitter-kafka-route
          image: shumyk/twitter-kafka-route
          volumeMounts:
            - name: twitter-kafka-config
              mountPath: /config/
          ports:
          - containerPort: 8080
          env:
          - name: TWITTER_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: twitter-kafka-route-secrets
                key: twitter.consumer.key
          - name: TWITTER_CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter-kafka-route-secrets
                key: twitter.consumer.secret
          - name: TWITTER_TOKEN
            valueFrom:
              secretKeyRef:
                name: twitter-kafka-route-secrets
                key: twitter.token
          - name: TWITTER_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter-kafka-route-secrets
                key: twitter.token.secret
      volumes:
        - name: twitter-kafka-config
          configMap:
            name: twitter-kafka-route-configmap